name: CI Pipeline

on:
  push:
    branches:
      - '*'
      - '!master' # Trigger on pushes to branches other than 'master'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ${{ github.workspace }}

      - name: Build changed projects
      # Check if any of the specified project directories have changes.
        run: |
          if git diff --name-only ${{ github.base_ref }}..${{ github.head_ref }} | grep -qE '^UtiliSense\\.(Gas|Grid|Solar|Water)/'; then
            echo "Building changed projects"
            # Build only the changed projects
            for project in UtiliSense.Gas UtiliSense.Grid UtiliSense.Solar UtiliSense.Water; do
              echo "Building $project"
              cd ${{ github.workspace }}/$project
              dotnet build $project.csproj
            done
          else
            echo "No changes in project directories. Skipping build."
          fi  
      - name: Build unit test projects
        run: |
          build_project() {
          echo "Build $1 project started"
          cd "${{ github.workspace }}/$1.Tests"
          echo "${{ github.workspace }}/$1"
          dotnet build "UtiliSense.Gas.UnitTests.csproj"
          echo "Build $1 project ended"
          }
          
          build_project "UtiliSense.Gas"


