name: CI Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ${{ github.workspace }}

      - name: Build modified projects
        run: |
            echo "Build UtiliSence.Gas project started"
            cd ${{ github.workspace }}/UtiliSence.Gas
            dotnet build UtiliSence.Gas.csproj

            echo "Build UtiliSence.Gas project ended"

            echo "Build UtiliSence.Grid project started"
            cd ${{ github.workspace }}/UtiliSence.Grid
            dotnet build UtiliSence.Grid.csproj

            echo "Build UtiliSence.Grid project ended"

            echo "Build UtiliSence.Solar project started"
            cd ${{ github.workspace }}/UtiliSence.Solar
            
            dotnet build UtiliSence.Solar.csproj

            echo "Build UtiliSence.Solar project ended"

            echo "Build UtiliSence.Water project started"
            cd ${{ github.workspace }}/UtiliSence.Water
            dotnet build UtiliSence.Water.csproj

            echo "Build UtiliSence.Water project ended"
