name: CI Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build modified projects
        run: |
            echo "Build UtiliSence.Gas project started"
            cd src/UtiliSence.Gas  # Adjust the directory path as per your project structure
            dotnet build UtiliSence.Gas.csproj
            dotnet build UtiliSence.Gas.Tests.csproj
            echo "Build UtiliSence.Gas project ended"

            echo "Build UtiliSence.Grid project started"
            cd src/UtiliSence.Grid  # Adjust the directory path as per your project structure
            dotnet build UtiliSence.Grid.csproj
            dotnet build UtiliSence.Grid.Tests.csproj
            echo "Build UtiliSence.Grid project ended"

            echo "Build UtiliSence.Solar project started"
            cd src/UtiliSence.Solar  # Adjust the directory path as per your project structure
            dotnet build UtiliSence.Solar.csproj
            dotnet build UtiliSence.Solar.Tests.csproj
            echo "Build UtiliSence.Solar project ended"

            echo "Build UtiliSence.Water project started"
            cd src/UtiliSence.Water  # Adjust the directory path as per your project structure
            dotnet build UtiliSence.Water.csproj
            dotnet build UtiliSence.Water.Tests.csproj
            echo "Build UtiliSence.Water project ended"
