name: CI Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ${{ github.workspace }}

      - name: Build modified projects
        run: |
            echo "Build UtiliSense.Gas project started"
            cd ${{ github.workspace }}/UtiliSence.Gas
            dotnet build UtiliSense.Gas.csproj
            dotnet build UtiliSense.Gas.Tests.csproj
            echo "Build UtiliSense.Gas project ended"

            echo "Build UtiliSense.Grid project started"
            cd ${{ github.workspace }}/UtiliSence.Grid
            dotnet build UtiliSense.Grid.csproj
            dotnet build UtiliSense.Grid.Tests.csproj
            echo "Build UtiliSense.Grid project ended"

            echo "Build UtiliSense.Solar project started"
            cd ${{ github.workspace }}/UtiliSence.Solar            
            dotnet build UtiliSense.Solar.csproj
            dotnet build UtiliSense.Solar.Tests.csproj
            echo "Build UtiliSense.Solar project ended"

            echo "Build UtiliSense.Water project started"
            cd ${{ github.workspace }}/UtiliSence.Water
            dotnet build UtiliSense.Water.csproj
            dotnet build UtiliSense.Water.Tests.csproj
            echo "Build UtiliSense.Water project ended"
