name: CI Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ${{ github.workspace }}

      - name: Build changed projects
        run: |
          # Check if the project directory has changes
          if git diff --name-only ${{ github.base_ref }}..${{ github.head_ref }} | grep -qE '^UtiliSense\\.(Gas|Grid|Solar|Water)/'; then
            echo "Building changed projects"
            # Build only the changed projects
            for project in UtiliSense.Gas UtiliSense.Grid UtiliSense.Solar UtiliSense.Water; do
              echo "Building $project"
              cd ${{ github.workspace }}/$project
              dotnet build $project.csproj
            done
          else
            echo "No changes in project directories. Skipping build."
          fi  

      - name: Build unit tests projects
        run: |
            echo "Build UtiliSense.Gas.Tests project started"
            cd ${{ github.workspace }}/UtiliSense.Gas.Tests
            dotnet build UtiliSense.Gas.Tests.csproj
            echo "Build UtiliSense.Gas.Tests project ended" 

            
            echo "Build UtiliSense.Grid.Tests project started"
            cd ${{ github.workspace }}/UtiliSense.Grid.Tests
            dotnet build UtiliSense.Grid.Tests.csproj
            echo "Build UtiliSense.Grid.Tests project ended"
            
            echo "Build UtiliSense.Solar.Tests project started"
            cd ${{ github.workspace }}/UtiliSense.Solar.Tests            
            dotnet build UtiliSense.Solar.Tests.csproj
            echo "Build UtiliSense.Solar.Tests project ended"
            
            echo "Build UtiliSense.Water.Tests project started"
            cd ${{ github.workspace }}/UtiliSense.Water.Tests
            dotnet build UtiliSense.Water.Tests.csproj
            echo "Build UtiliSense.Water.Tests project ended"
            
      - name: Run unit tests projects
        run: dotnet test
